name: cs7641hw4
dependencies:
- python=3.7
- matplotlib=3.1.3
- numpy=1.18.1
- pandas=1.0.3
- scikit-learn=0.22.0
- scipy==1.4.1
- seaborn==0.10.1
- pip=20.0.2
- future=0.17.1
- pip=20.0.2
- pytest=5.0
- pyparsing=2.4.0
- pip:
  - mlrose==1.3.0
  - mlrose_hiive==2.1.3
  - gym==0.17.3  
  - MDP==3.5
  - mdptoolbox-hiive==4.0.3.1
  - more-itertools==8.5.0
  - py==1.9.0
  - pydot==1.4.1
  - pyglet==1.5.0
  - pymdptoolbox==4.0b3
  - tables==3.6.1
  - dataframe_image